//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int id { get; set; }
        public int UnitPrice { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int NumberOfEmployee { get; set; }
        public int Status { get; set; }
        public int Service_Id { get; set; }
        public int OrderService_Id { get; set; }
    
        public virtual OrderService OrderService { get; set; }
        public virtual Service Service { get; set; }
    }
}
